info:
  app:
    name: @project.artifactId@
    version: @project.version@
spring:
#  data:
#    mongodb:
#      auto-index-creation: true
  output:
    ansi:
      enabled: always
kafka:
  bootstrap:
    address: localhost
    port: 29092
  consumer:
    auto-offset-reset: earliest
    topic: person-topic
    group-id: person-group
#mongo:
#  url: mongodb://root:example@localhost:27017/test?authSource=admin
#  table-name: test