info:
  app:
    name: @project.artifactId@
    version: @project.version@
spring:
  server:
    port: 8086
#  application:
#    name: presight.ai.neo4j
  output:
    ansi:
      enabled: always
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: secret

  #spring.thymeleaf.cache=false
  #
  #spring.servlet.multipart.max-file-size=256MB
  #spring.servlet.multipart.max-request-size=256MB
  #spring.servlet.multipart.enabled=true

kafka:
  bootstrap:
    address: localhost
    port: 29092
  consumer:
    auto-offset-reset: earliest
    calls-topic: calls-topic
    calls-group-id: calls-group